language: python
python:
  - '3.6'

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run api sh -c "pipenv run python manage.py test && pipenv run black . && pipenv run flake8"

